version: "3.8"

services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=frourio
      - DATABASE_HOST=localhost

  db-shadow:
    image: postgres:12
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=frourio-shadow
      - DATABASE_HOST=localhost
